#!/bin/bash

# namesort bam for Genrich
# To run Genrich, the bam has to be namesorted.  If using another peak caller dont need this

samtools sort -@ 5 -n <sample>_nodups_nomulti_filtered.bam  > <sample>_nodups_nomulti_filtered_namesorted.bam

Genrich \
-t <sample>_nodups_nomulti_filtered_namesorted.bam \
-o <sample>_nodups_nomulti_filtered_namesorted_peaks \
-j \
-v \
-p 0.01 \
-a 200

---------------------------------------------------------------------------------------------------------------------

# run IDR on two replicates to get reproducible peaks
# this is assuming you have two replicates run through the previous commands, now sample_1 and sample_2
# Alternatively, Genrich can also handle handle replicates and create a consensus, see the Genrich documentation

idr --samples <sample_1>_nodups_nomulti_filtered_namesorted_peaks <sample_2>_nodups_nomulti_filtered_namesorted_peaks \
--output-file-type narrowPeak  \
--output-file <sample>_IDR.narrowPeak

---------------------------------------------------------------------------------------------------------------------
